Repository OHIF/Viewers, pull requests merged in 2019-12, with the labels that each got.

#1218 refactor: Viewports state
  extensions/cornerstone/src/ConnectedCornerstoneViewport.js
  extensions/cornerstone/src/commandsModule.js
  extensions/cornerstone/src/state.js
  extensions/dicom-html/src/ConnectedDicomHtmlViewport.js
  extensions/dicom-html/src/DicomHtmlViewport.js
  extensions/vtk/src/commandsModule.js
  extensions/vtk/src/index.js
  platform/core/src/extensions/ExtensionManager.js
  platform/core/src/extensions/ExtensionManager.test.js
  platform/core/src/redux/actions.js
  platform/core/src/redux/actions.test.js
  platform/core/src/redux/reducers/viewports.js
  platform/core/src/redux/reducers/viewports.test.js
  platform/viewer/src/connectedComponents/ConnectedCineDialog.js
  platform/viewer/src/connectedComponents/ConnectedViewportDownloadForm.js
Labels: PR: Awaiting Response :speech_balloon:

#1239 Refactor/viewports store
  extensions/cornerstone/src/CornerstoneViewportDownloadForm.js
  extensions/cornerstone/src/commandsModule.js
  extensions/cornerstone/src/index.js
  platform/viewer/src/connectedComponents/ConnectedViewportDownloadForm.js
  platform/viewer/src/connectedComponents/ToolbarRow.js
Labels: PR: Awaiting Revisions :pen:

#1245 docs: process updates labels deploy
  docs/latest/our-process.md
Labels: PR: No UX Impact :upside_down_face:

#1272 refactor: 💡 ServicesManager factory functions vs instances
  docs/latest/services/ui/index.md
  platform/core/src/index.js
  platform/core/src/index.test.js
  platform/core/src/services/ServicesManager.js
  platform/core/src/services/ServicesManager.test.js
  platform/core/src/services/UIContextMenuService/index.js
  platform/core/src/services/UIDialogService/index.js
  platform/core/src/services/UILabellingFlowService/index.js
  platform/core/src/services/UIModalService/index.js
  platform/core/src/services/UINotificationService/index.js
  platform/core/src/services/index.js
  platform/viewer/src/App.js
  yarn.lock
Labels: PR: No UX Impact :upside_down_face:

#1277 Igor/refactor/1267 remove labelling manager
  extensions/cornerstone/src/init.js
  platform/viewer/public/config/default.js
  platform/viewer/src/App.js
  platform/viewer/src/components/Labelling/LabellingFlow.css
  platform/viewer/src/components/Labelling/LabellingFlow.js
  platform/viewer/src/components/Labelling/LabellingManager.js
Labels: PR: No UX Impact :upside_down_face:

#1219 E2E Tests: Download Image File Modal
  platform/ui/src/components/content/viewportDownloadForm/ViewportDownloadForm.js
  platform/ui/src/components/ohifModal/OHIFModal.js
  platform/viewer/cypress/integration/common/OHIFCornerstoneHotkeys.spec.js
  platform/viewer/cypress/integration/common/OHIFDownloadSnapshotFile.spec.js
  platform/viewer/cypress/support/aliases.js
  platform/viewer/cypress/support/commands.js
Labels: Task: Tests :microscope:

#1293 Chore/upgrade cypress version
  .circleci/config.yml
  platform/viewer/package.json
  yarn.lock
Labels: PR: No UX Impact :upside_down_face:, Task: CI/Tooling :robot:

#1294 Chore/upgrade cypress version
  .circleci/config.yml
  platform/viewer/cypress.json
  platform/viewer/package.json
Labels: PR: No UX Impact :upside_down_face:, Task: CI/Tooling :robot:

#1295 fix: allow empty values for dimensions
  platform/ui/src/components/content/viewportDownloadForm/ViewportDownloadForm.js
Labels: Task: Tests :microscope:

#1292 refactor: Remove LabelingFlow/ContextMenu services and reimplement on top of the Dialog service #1264
  platform/core/src/index.js
  platform/core/src/index.test.js
  platform/core/src/services/UIContextMenuService/index.js
  platform/core/src/services/UILabellingFlowService/index.js
  platform/core/src/services/index.js
  platform/ui/src/components/contextMenu/ContextMenu.css
  platform/ui/src/components/contextMenu/ContextMenu.js
  platform/ui/src/components/contextMenu/index.js
  platform/ui/src/components/index.js
  platform/ui/src/contextProviders/ContextMenuProvider.js
  platform/ui/src/contextProviders/LabellingFlowProvider.js
  platform/ui/src/contextProviders/index.js
  platform/ui/src/index.js
  platform/viewer/src/App.js
  platform/viewer/src/appCustomProviders/ContextMenuProvider/ContextMenuProvider.js
  platform/viewer/src/appCustomProviders/LabellingFlowProvider/LabellingFlowProvider.js
  platform/viewer/src/appCustomProviders/index.js
  platform/viewer/src/appExtensions/MeasurementsPanel/index.js
  platform/viewer/src/appExtensions/MeasurementsPanel/init.js
  platform/viewer/src/connectedComponents/ToolContextMenu.js
Labels: PR: No UX Impact :upside_down_face:, Task: Refactor :hammer_and_wrench:

#1299 refactor: 💡 Use env variables to set locize
  .webpack/webpack.base.js
  platform/i18n/src/index.js
Labels: PR: No UX Impact :upside_down_face:, Task: Refactor :hammer_and_wrench:

#1302 fix: 🐛 add WwwcRegionTool to cornerstone tools initialization
  extensions/cornerstone/src/init.js
Labels: PR: Bug Fix :bug:, PR: No UX Impact :upside_down_face:

#1279 feat: 🎸 Expose extension config to modules
  docs/latest/extensions/index.md
  extensions/_example/src/index.js
  platform/core/src/extensions/ExtensionManager.js
  platform/core/src/extensions/ExtensionManager.test.js
  platform/core/src/services/ServicesManager.js
  platform/core/src/services/ServicesManager.test.js
  platform/viewer/src/App.js
Labels: Extension: Discussion, PR: No UX Impact :upside_down_face:, Story :raised_hands:

#1310 refactor: 💡 Move DICOMSR code to @ohif/core project
  platform/core/package.json
  platform/core/src/DICOMSR/dataExchange.js
  platform/core/src/DICOMSR/handleStructuredReport.js
  platform/core/src/DICOMSR/index.js
  platform/core/src/DICOMSR/parseDicomStructuredReport.js
  platform/core/src/DICOMSR/parseMeasurementsData.js
  platform/core/src/DICOMSR/utils/findInstanceMetadataBySopInstanceUid.js
  platform/core/src/DICOMSR/utils/findMostRecentStructuredReport.js
  platform/core/src/DICOMSR/utils/getAllDisplaySets.js
  platform/core/src/DICOMSR/utils/isToolSupported.js
  platform/core/src/index.js
  platform/core/src/index.test.js
  platform/viewer/src/appExtensions/MeasurementsPanel/ConnectedMeasurementTable.js
  platform/viewer/src/connectedComponents/Viewer.js
  yarn.lock
Labels: PR: No UX Impact :upside_down_face:, Task: Refactor :hammer_and_wrench:

#1300 E2E Tests: Save Measurements Functionality
  platform/ui/src/components/measurementTable/MeasurementTable.js
  platform/viewer/cypress/integration/pwa/OHIFSaveMeasurements.spec.js
Labels: Task: Tests :microscope:

#1323 Refactoring toolbar data-cy selectors
  platform/ui/src/components/userPreferencesForm/UserPreferencesTabs.js
  platform/ui/src/viewer/ToolbarButton.js
  platform/viewer/cypress/integration/common/OHIFCornerstoneToolbar.spec.js
  platform/viewer/cypress/integration/pwa/OHIFExtensionVTK.spec.js
  platform/viewer/cypress/support/aliases.js
  platform/viewer/cypress/support/commands.js
Labels: Task: Tests :microscope:

#1322 fix: 🐛 1241: Make Plugin switch part of ToolbarModule
  .gitignore
  extensions/cornerstone/src/commandsModule.js
  extensions/cornerstone/src/toolbarModule.js
  extensions/cornerstone/src/utils/setCornerstoneLayout.js
  extensions/vtk/src/toolbarComponents/VTKMPRToolbarButton.js
  extensions/vtk/src/toolbarModule.js
  platform/core/src/extensions/ExtensionManager.test.js
  platform/viewer/cypress/support/aliases.js
  platform/viewer/src/connectedComponents/ConnectedPluginSwitch.js
  platform/viewer/src/connectedComponents/PluginSwitch.css
  platform/viewer/src/connectedComponents/PluginSwitch.js
  platform/viewer/src/connectedComponents/ToolbarRow.js
Labels: PR: Bug Fix :bug:

#1324 test: 💍 Updating tests after bug fix
  platform/viewer/cypress/integration/pwa/OHIFExtensionVTK.spec.js
Labels: PR: No UX Impact :upside_down_face:

#1337 chore: throw our error if we encounter one (no swallow)
  platform/core/src/studies/services/wado/retrieveMetadataLoader.js
Labels: PR: No UX Impact :upside_down_face:
