Repository OHIF/Viewers, pull requests merged in 2019-10, with the labels that each got.

#947 Issue 924 toolbar custom mip
  extensions/vtk/src/commandsModule.js
  extensions/vtk/src/toolbarComponents/SlabThicknessToolbarComponent.js
  extensions/vtk/src/toolbarComponents/slab-thickness-toolbar-button.styl
  extensions/vtk/src/toolbarModule.js
  platform/ui/src/components/checkbox/checkbox.js
  platform/ui/src/components/index.js
  platform/ui/src/elements/form/Range.css
  platform/ui/src/elements/form/Range.js
  platform/ui/src/elements/form/Select.css
  platform/ui/src/elements/form/Select.js
  platform/ui/src/index.js
  platform/ui/src/viewer/ExpandableToolMenu.js
  platform/viewer/src/connectedComponents/ToolbarRow.js
Labels: PR: Awaiting Review :eyes:

#1012 feat: saner react cornerstone extension update
  extensions/cornerstone/package.json
  extensions/cornerstone/src/ConnectedCornerstoneViewport.js
  extensions/cornerstone/src/OHIFCornerstoneViewport.js
  extensions/cornerstone/src/index.js
  extensions/cornerstone/src/init.js
  extensions/cornerstone/src/initCornerstoneTools.js
  platform/viewer/src/App.js
  platform/viewer/src/appExtensions/MeasurementsPanel/ConnectedMeasurementTable.js
  platform/viewer/src/appExtensions/MeasurementsPanel/actions.js
  platform/viewer/src/appExtensions/MeasurementsPanel/getMeasurementLocationCallback.js
  platform/viewer/src/appExtensions/MeasurementsPanel/index.js
  platform/viewer/src/appExtensions/MeasurementsPanel/init.js
  platform/viewer/src/appExtensions/MeasurementsPanel/labelingFlowCallbacks.js
  platform/viewer/src/appExtensions/MeasurementsPanel/updateTableWithNewMeasurementData.js
  platform/viewer/src/connectedComponents/ConnectedToolContextMenu.js
  platform/viewer/src/connectedComponents/ToolContextMenu.js
  platform/viewer/src/setupTools.js
  yarn.lock
Labels: PR: Awaiting Review :eyes:

#1037 feat: Implement a 'Exit 2D MPR' button in the toolbar to act as a tog…
  platform/viewer/src/connectedComponents/ConnectedPluginSwitch.js
  platform/viewer/src/connectedComponents/PluginSwitch.js
Labels: PR: Awaiting Revisions :pen:

#1011 feat: Notification Service
  platform/ui/src/components/snackbar/Snackbar.css
  platform/ui/src/components/snackbar/SnackbarContainer.js
  platform/ui/src/components/snackbar/SnackbarItem.js
  platform/ui/src/components/snackbar/SnackbarTypes.js
  platform/ui/src/index.js
  platform/ui/src/utils/SnackbarProvider.js
  platform/viewer/src/App.js
  platform/viewer/src/variables.css
Labels: PR: Awaiting Revisions :pen:

#840 feat: Snapshot Download Tool
  .vscode/settings.json
  extensions/cornerstone/src/toolbarModule.js
  platform/core/src/utils/b64toBlob.js
  platform/core/src/utils/index.js
  platform/core/src/utils/index.test.js
  platform/ui/src/components/downloadDialog/DownloadDialog.js
  platform/ui/src/components/downloadDialog/DownloadDialog.styl
  platform/ui/src/components/downloadDialog/__docs__/downloadDialog.mdx
  platform/ui/src/components/downloadDialog/index.js
  platform/ui/src/components/index.js
  platform/ui/src/elements/form/Select.css
  platform/ui/src/elements/form/Select.js
  platform/ui/src/elements/form/TextInput.css
  platform/ui/src/elements/form/TextInput.js
  platform/ui/src/elements/index.js
  platform/ui/src/index.js
  platform/viewer/src/connectedComponents/ConnectedDownloadDialog.js
  platform/viewer/src/connectedComponents/ToolbarRow.js
  platform/viewer/src/theme-tide.css
Labels: PR: Awaiting Revisions :pen:

#1068 feat: responsive study list
  platform/ui/package.json
  platform/ui/src/components/index.js
  platform/ui/src/components/studyList/CustomDateRangePicker.css
  platform/ui/src/components/studyList/CustomDateRangePicker.js
  platform/ui/src/components/studyList/CustomDateRangePicker.styl
  platform/ui/src/components/studyList/PageToolbar.js
  platform/ui/src/components/studyList/PaginationArea.styl
  platform/ui/src/components/studyList/StudyList.js
  platform/ui/src/components/studyList/StudyList.styl
  platform/ui/src/components/studyList/StudyListLoadingText.js
  platform/ui/src/components/studyList/StudyListToolbar.styl
  platform/ui/src/components/studyList/TablePagination.js
  platform/ui/src/components/studyList/TableSearchFilter.js
  platform/ui/src/components/studyList/index.js
  platform/ui/src/components/studyList/internal/bkdr-hash.js
  platform/ui/src/components/studyList/internal/color-hash.js
  platform/ui/src/components/userPreferencesModal/AboutModal.js
  platform/ui/src/design/styles/common/global.styl
  platform/ui/src/hooks/index.js
  platform/ui/src/hooks/useDebounce.js
  platform/ui/src/hooks/useMedia.js
  platform/ui/src/index.js
  platform/viewer/cypress/integration/common/OHIFStandaloneViewer.spec.js
  platform/viewer/cypress/integration/common/ViewerRouting.spec.js
  platform/viewer/cypress/support/commands.js
  platform/viewer/src/App.js
  platform/viewer/src/components/Header/Header.css
  platform/viewer/src/components/Header/Header.js
  platform/viewer/src/components/OHIFLogo/OHIFLogo.css
  platform/viewer/src/components/OHIFLogo/OHIFLogo.js
  platform/viewer/src/components/SidePanel.css
  platform/viewer/src/studylist/ConnectedStudyList.js
  platform/viewer/src/studylist/StudyListRoute.js
  platform/viewer/src/studylist/StudyListWithData.js
  yarn.lock
Labels: PR: Awaiting Review :eyes:

#1118 fix: Set SR viewport as active by interaction
  .eslintrc.json
  extensions/dicom-html/src/ConnectedDicomHtmlViewport.js
  extensions/dicom-html/src/DicomHtmlViewport.js
  extensions/dicom-html/src/OHIFDicomHtmlViewport.js
  platform/viewer/cypress/integration/pwa/OHIFExtensionHTML.spec.js
  platform/viewer/cypress/support/commands.js
Labels: PR: Awaiting Response :speech_balloon:

#1112 fix: 🐛 Limit image download size to avoid browser issues
  platform/ui/src/components/downloadDialog/DownloadDialog.js
  platform/viewer/src/connectedComponents/ConnectedDownloadDialog.js
Labels: PR: Awaiting Response :speech_balloon:, PR: Awaiting Revisions :pen:

#1113 fix: 🐛 Fix ghost shadow on thumb
  platform/ui/package.json
  platform/ui/src/components/index.js
  platform/ui/src/components/quickSwitch/QuickSwitch.styl
  platform/ui/src/components/quickSwitch/SeriesList.js
  platform/ui/src/components/studyBrowser/DragPreview.js
  platform/ui/src/components/studyBrowser/DragPreview.styl
  platform/ui/src/components/studyBrowser/StudyBrowser.js
  platform/ui/src/components/studyBrowser/StudyBrowser.styl
  platform/ui/src/components/studyBrowser/Thumbnail.js
  platform/ui/src/components/studyBrowser/Thumbnail.styl
  platform/ui/src/components/studyBrowser/ThumbnailEntry.js
  platform/ui/src/components/studyBrowser/ThumbnailEntryDragSource.js
  platform/ui/src/components/studyBrowser/index.js
  platform/ui/src/index.js
  platform/viewer/cypress/integration/common/ViewerRouting.spec.js
  platform/viewer/src/components/ViewportGrid/ViewportGrid.js
Labels: PR: Awaiting Review :eyes:
