Repository OHIF/Viewers, pull requests merged in 2019-11, with the labels that each got.

#1090 fix: #1075 Returning to the Study List before all series have finishe…
  platform/core/src/utils/index.js
  platform/core/src/utils/index.test.js
  platform/core/src/utils/makeCancelable.js
  platform/ui/src/components/studyBrowser/ImageThumbnail.js
  platform/viewer/src/connectedComponents/ViewerRetrieveStudyData.js
Labels: PR: Awaiting Revisions :pen:

#1116 feat: 🎸 Update AboutModal to use new modal provider
  extensions/vtk/CHANGELOG.md
  extensions/vtk/package.json
  platform/i18n/src/locales/en-US/index.js
  platform/i18n/src/locales/pt-BR/index.js
  platform/ui/CHANGELOG.md
  platform/ui/package.json
  platform/ui/src/components/content/aboutContent/AboutContent.js
  platform/ui/src/components/content/aboutContent/AboutContent.styl
  platform/ui/src/components/index.js
  platform/ui/src/components/measurementTable/MeasurementTableItem.styl
  platform/ui/src/components/tableList/TableListItem.styl
  platform/ui/src/components/userPreferencesModal/AboutModal.js
  platform/ui/src/components/userPreferencesModal/__docs__/about.mdx
  platform/ui/src/components/userPreferencesModal/index.js
  platform/ui/src/index.js
  platform/viewer/CHANGELOG.md
  platform/viewer/cypress/integration/common/OHIFCornerstoneToolbar.spec.js
  platform/viewer/package.json
  platform/viewer/src/appExtensions/MeasurementsPanel/ConnectedMeasurementTable.js
  platform/viewer/src/appExtensions/MeasurementsPanel/labelingFlowCallbacks.js
  platform/viewer/src/components/Header/Header.js
  platform/viewer/src/components/Labelling/LabellingFlow.js
  platform/viewer/src/components/ViewportGrid/ViewportPane.js
  yarn.lock
Labels: PR: Awaiting Revisions :pen:

#1148 feat: 🎸 Change ImageThumb to functional and change thumb on upd
  platform/ui/src/components/studyBrowser/ImageThumbnail.js
  platform/ui/src/components/studyBrowser/StudyBrowser.js
Labels: PR: Awaiting Review :eyes:

#1157 fix: mpr2d vtkjs viewport does not render if range is set to `NaN` values
  extensions/vtk/src/OHIFVTKViewport.js
  extensions/vtk/src/commandsModule.js
Labels: IDC:priority

#1170 filter field for google windows
  platform/viewer/src/googleCloud/DatasetPicker.js
  platform/viewer/src/googleCloud/DatasetsList.js
  platform/viewer/src/googleCloud/DicomStoreList.js
  platform/viewer/src/googleCloud/DicomStorePicker.js
  platform/viewer/src/googleCloud/LocationPicker.js
  platform/viewer/src/googleCloud/LocationsList.js
  platform/viewer/src/googleCloud/ProjectPicker.js
  platform/viewer/src/googleCloud/ProjectsList.js
  platform/viewer/src/googleCloud/googleCloud.css
Labels: PR: Awaiting Revisions :pen:

#1153 improvement: Date Picker
  platform/i18n/src/locales/en-US/Common.json
  platform/i18n/src/locales/en-US/DatePicker.json
  platform/i18n/src/locales/en-US/index.js
  platform/i18n/src/locales/pt-BR/Common.json
  platform/i18n/src/locales/pt-BR/DatePicker.json
  platform/i18n/src/locales/pt-BR/index.js
  platform/ui/src/components/studyList/CustomDateRangePicker.css
  platform/ui/src/components/studyList/CustomDateRangePicker.js
  platform/ui/src/components/studyList/StudyList.js
  platform/ui/src/components/studyList/StudyList.styl
  platform/ui/src/components/studyList/TableSearchFilter.js
  platform/viewer/src/studylist/StudyListRoute.js
  platform/viewer/src/variables.css
Labels: PR: Awaiting Response :speech_balloon:

#1141 Issue 879 viewer route query param not filtering but promoting
  platform/core/src/studies/services/wado/retrieveMetadataLoader.js
  platform/core/src/studies/studyUtils.js
  platform/ui/src/components/studyBrowser/ImageThumbnail.js
  platform/viewer/cypress/integration/common/OHIFStudyList.spec.js
  platform/viewer/public/config/default.js
  platform/viewer/src/connectedComponents/ConnectedViewerRetrieveStudyData.js
  platform/viewer/src/connectedComponents/ViewerRetrieveStudyData.js
Labels: PR: Awaiting Review :eyes:

#1202 feat: New dialog service
  extensions/cornerstone/src/toolbarModule.js
  platform/core/src/index.js
  platform/core/src/index.test.js
  platform/core/src/services/UIDialogService/index.js
  platform/core/src/services/UIModalService/index.js
  platform/core/src/services/index.js
  platform/ui/package.json
  platform/ui/src/components/cineDialog/CineDialog.js
  platform/ui/src/components/content/aboutContent/AboutContent.js
  platform/ui/src/components/content/viewportDownloadForm/ViewportDownloadForm.js
  platform/ui/src/components/content/viewportDownloadForm/ViewportDownloadForm.styl
  platform/ui/src/components/languageSwitcher/LanguageSwitcher.js
  platform/ui/src/components/measurementTable/MeasurementTable.js
  platform/ui/src/components/measurementTable/MeasurementTableItem.js
  platform/ui/src/components/ohifModal/OHIFModal.js
  platform/ui/src/components/ohifModal/OHIFModal.styl
  platform/ui/src/components/overlayTrigger/Overlay.js
  platform/ui/src/components/snackbar/SnackbarContainer.js
  platform/ui/src/components/studyList/StudyList.js
  platform/ui/src/components/studyList/StudyListLoadingText.js
  platform/ui/src/components/studyList/TablePagination.js
  platform/ui/src/components/userPreferencesForm/HotKeysPreferences.styl
  platform/ui/src/components/userPreferencesForm/UserPreferences.js
  platform/ui/src/components/userPreferencesForm/UserPreferences.styl
  platform/ui/src/components/userPreferencesForm/UserPreferencesForm.js
  platform/ui/src/components/userPreferencesForm/UserPreferencesForm.styl
  platform/ui/src/contextProviders/DialogProvider.js
  platform/ui/src/contextProviders/DialogProvider.styl
  platform/ui/src/contextProviders/LanguageProvider.js
  platform/ui/src/contextProviders/ModalProvider.js
  platform/ui/src/contextProviders/SnackbarProvider.js
  platform/ui/src/contextProviders/index.js
  platform/ui/src/index.js
  platform/ui/src/viewer/ToolbarButton.js
  platform/viewer/cypress/integration/common/OHIFStudyViewer.spec.js
  platform/viewer/src/App.js
  platform/viewer/src/components/Header/Header.js
  platform/viewer/src/connectedComponents/ToolbarRow.js
  yarn.lock
Labels: PR: Awaiting Revisions :pen:

#1195 Test Cases for User Preferences
  platform/ui/src/components/userPreferencesForm/UserPreferencesForm.js
  platform/viewer/cypress/integration/common/OHIFCornerstoneHotkeys.spec.js
  platform/viewer/cypress/integration/common/OHIFUserPreferences.spec.js
  platform/viewer/cypress/support/aliases.js
  platform/viewer/cypress/support/commands.js
Labels: PR: Awaiting Response :speech_balloon:

#1150 Issue branch from danny experimental changes pr 1128
  platform/ui/src/components/studyList/StudyList.js
  platform/ui/src/components/studyList/TableSearchFilter.js
  platform/ui/src/hooks/index.js
  platform/ui/src/hooks/useMedia.js
  platform/viewer/src/studylist/StudyListRoute.js
Labels: PR: Awaiting Review :eyes:

#1207 fix: User Preferences Issues
  platform/core/src/classes/HotkeysManager.js
  platform/core/src/classes/HotkeysManager.test.js
  platform/core/src/redux/reducers/preferences.js
  platform/i18n/src/index.js
  platform/i18n/src/locales/ar/UserPreferencesModal.json
  platform/i18n/src/locales/ar/index.js
  platform/i18n/src/locales/en-US/UserPreferencesModal.json
  platform/i18n/src/locales/index.js
  platform/i18n/src/locales/pt-BR/UserPreferencesModal.json
  platform/ui/src/components/languageSwitcher/LanguageSwitcher.js
  platform/ui/src/components/studyList/CustomDateRangePicker.js
  platform/ui/src/components/studyList/StudyList.js
  platform/ui/src/components/studyList/TableSearchFilter.js
  platform/ui/src/components/userPreferencesForm/GeneralPreferences.js
  platform/ui/src/components/userPreferencesForm/HotKeysPreferences.js
  platform/ui/src/components/userPreferencesForm/UserPreferences.js
  platform/ui/src/components/userPreferencesForm/UserPreferencesForm.js
  platform/ui/src/components/userPreferencesForm/UserPreferencesTabs.js
  platform/ui/src/components/userPreferencesForm/UserPreferencesTabs.styl
  platform/ui/src/components/userPreferencesForm/WindowLevelPreferences.js
  platform/ui/src/components/userPreferencesForm/WindowLevelPreferences.styl
  platform/ui/src/components/userPreferencesForm/index.js
  platform/ui/src/elements/form/DropdownMenu.js
  platform/viewer/cypress/integration/common/OHIFStudyViewer.spec.js
  platform/viewer/cypress/integration/common/OHIFUserPreferences.spec.js
  platform/viewer/cypress/support/commands.js
  platform/viewer/src/App.js
  platform/viewer/src/components/Header/Header.js
  platform/viewer/src/connectedComponents/ConnectedHeader.js
  platform/viewer/src/connectedComponents/ConnectedUserPreferencesForm.js
  platform/viewer/src/variables.css
Labels: PR: Awaiting Review :eyes:
