Repository OHIF/Viewers, pull requests merged in 2019-09, with the labels that each got.

#870 feat: 🎸 Load local file or folder using native dialog
  platform/viewer/src/connectedComponents/ViewerLocalFileData.css
  platform/viewer/src/connectedComponents/ViewerLocalFileData.js
Labels: PR: Awaiting Revisions :pen:

#912 feat(Eraser Tool)
  extensions/cornerstone/src/toolbarModule.js
  platform/ui/src/elements/Icon/getIcon.js
  platform/ui/src/elements/Icon/icons/eraser.svg
Labels: PR: Awaiting Review :eyes:

#911 feat(Bidirectional Tool)
  extensions/cornerstone/src/toolbarModule.js
Labels: PR: Awaiting Review :eyes:

#935 feat: 🎸 React custom component on toolbar button
  docs/latest/advanced/extensions.md
  platform/viewer/src/connectedComponents/ToolbarRow.js
Labels: PR: Awaiting Review :eyes:

#906 #724 Fonts refactor
  platform/viewer/.webpack/webpack.pwa.js
  platform/viewer/public/html-templates/rollbar.html
  platform/viewer/src/fonts/KFOmCnqEu92Fr1Mu4WxKKTU1Kvnz.woff2
  platform/viewer/src/fonts/KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2
  platform/viewer/src/fonts/KFOmCnqEu92Fr1Mu5mxKKTU1Kvnz.woff2
  platform/viewer/src/fonts/KFOmCnqEu92Fr1Mu72xKKTU1Kvnz.woff2
  platform/viewer/src/fonts/KFOmCnqEu92Fr1Mu7GxKKTU1Kvnz.woff2
  platform/viewer/src/fonts/KFOmCnqEu92Fr1Mu7WxKKTU1Kvnz.woff2
  platform/viewer/src/fonts/KFOmCnqEu92Fr1Mu7mxKKTU1Kvnz.woff2
  platform/viewer/src/fonts/fonts.css
  platform/viewer/src/index-umd.js
Labels: PR: Awaiting Response :speech_balloon:
