Repository OHIF/Viewers, pull requests merged in 2020-01, with the labels that each got.

#1360 fix: 🐛 Metadata is being mistakenly purged
  platform/viewer/src/connectedComponents/ViewerRetrieveStudyData.js
Labels: PR: Awaiting Review :eyes:

#1384 Visual tests: Fixed ci config for visual tests (percy)
  .circleci/config.yml
Labels: Task: Tests :microscope:

#1379 1316 - E2E tests for /local
  package.json
  platform/viewer/cypress/fixtures/PDFDICOMfile.pdf
  platform/viewer/cypress/integration/common/OHIFLoadLocalFile.spec.js
  platform/viewer/cypress/integration/pwa/OHIFLoadLocalPDFFile.spec.js
  platform/viewer/cypress/support/commands.js
  yarn.lock
Labels: Task: Tests :microscope:

#1139 fix: Set VTK viewport as active by interaction
  extensions/vtk/package.json
  extensions/vtk/src/ConnectedVTKViewport.js
  extensions/vtk/src/OHIFVTKViewport.js
  extensions/vtk/src/VTKViewport.css
  extensions/vtk/src/VTKViewport.js
  extensions/vtk/src/commandsModule.js
  extensions/vtk/src/index.js
  extensions/vtk/src/withCommandsManager.js
  platform/core/src/classes/CommandsManager.js
  yarn.lock
Labels: Story :raised_hands:
