Repository OHIF/Viewers, pull requests merged in 2020-04, with the labels that each got.

#1582 Switch asyncComponent to React Lazy/Suspense (Issue #1577)
  extensions/cornerstone/src/asyncComponent.js
  extensions/cornerstone/src/index.js
  extensions/dicom-html/src/asyncComponent.js
  extensions/dicom-html/src/index.js
  extensions/dicom-microscopy/src/asyncComponent.js
  extensions/dicom-microscopy/src/index.js
  extensions/dicom-pdf/src/asyncComponent.js
  extensions/dicom-pdf/src/index.js
Labels: Community: PR :tada:, PR: Awaiting Review :eyes:

#1575 Reduce bundle size
  extensions/vtk/src/OHIFVTKViewport.js
  extensions/vtk/src/VTKViewport.js
  extensions/vtk/src/commandsModule.js
  extensions/vtk/src/utils/getReactVtkjsViewport.js
  platform/core/src/classes/StudyLoadingListener.js
  platform/core/src/studies/services/wado/studyInstanceHelpers.js
  platform/core/src/utils/cornerstoneWADOImageLoader.js
  platform/core/src/utils/dicomLoaderService.js
  platform/viewer/src/App.js
  platform/viewer/src/config.js
  platform/viewer/src/lib/filesToStudies.js
  platform/viewer/src/lib/localFileLoaders/dicomFileLoader.js
  platform/viewer/src/lib/localFileLoaders/fileLoaderService.js
  platform/viewer/src/lib/localFileLoaders/pdfFileLoader.js
  platform/viewer/src/routes/routesUtil.js
  platform/viewer/src/utils/cornerstoneWADOImageLoader.js
  platform/viewer/src/utils/index.js
  platform/viewer/src/utils/index.test.js
  platform/viewer/src/utils/initWebWorkers.js
  platform/viewer/src/utils/initWebWorkers.test.js
Labels: Community: PR :tada:

#1524 Support of RTSTRUCT visualization
  extensions/cornerstone/src/commandsModule.js
  extensions/dicom-rt/.webpack/webpack.dev.js
  extensions/dicom-rt/.webpack/webpack.prod.js
  extensions/dicom-rt/LICENSE
  extensions/dicom-rt/README.md
  extensions/dicom-rt/package.json
  extensions/dicom-rt/src/OHIFDicomRTStructSopClassHandler.js
  extensions/dicom-rt/src/components/LoadingIndicator/LoadingIndicator.js
  extensions/dicom-rt/src/components/PanelSection/PanelSection.css
  extensions/dicom-rt/src/components/PanelSection/PanelSection.js
  extensions/dicom-rt/src/components/RTPanel/RTPanel.css
  extensions/dicom-rt/src/components/RTPanel/RTPanel.js
  extensions/dicom-rt/src/components/RTSettings/RTSettings.css
  extensions/dicom-rt/src/components/RTSettings/RTSettings.js
  extensions/dicom-rt/src/components/StructureSetItem/StructureSetItem.css
  extensions/dicom-rt/src/components/StructureSetItem/StructureSetItem.js
  extensions/dicom-rt/src/id.js
  extensions/dicom-rt/src/index.js
  extensions/dicom-rt/src/init.js
  extensions/dicom-rt/src/loadRTStruct.js
  extensions/dicom-rt/src/tools/RTStructDisplayTool.js
  extensions/dicom-rt/src/tools/modules/lib/getImageIdOfCenterFrameOfROIContour.js
  extensions/dicom-rt/src/tools/modules/lib/structureSetReferencesSeriesInstanceUid.js
  extensions/dicom-rt/src/tools/modules/rtStructModule.js
  extensions/dicom-rt/src/utils/toolNames.js
  extensions/dicom-rt/src/utils/transformPointsToImagePlane.js
  extensions/dicom-segmentation/src/components/SegmentationPanel/SegmentationPanel.js
  extensions/vtk/CHANGELOG.md
  platform/core/CHANGELOG.md
  platform/core/src/studies/services/wado/studyInstanceHelpers.js
  platform/ui/CHANGELOG.md
  platform/ui/src/components/tableList/TableList.js
  platform/ui/src/elements/Icon/getIcon.js
  platform/ui/src/elements/Icon/icons/eye-closed.svg
  platform/ui/src/elements/Icon/icons/eye.svg
  platform/viewer/CHANGELOG.md
  platform/viewer/package.json
  platform/viewer/src/index.js
  yarn.lock
Labels: PR: Awaiting Revisions :pen:
