Repository OHIF/Viewers, pull requests merged in 2020-06, with the labels that each got.

#1734 fix: 🐛 Infinite frame index change when quickly jumping between
  extensions/cornerstone/package.json
  extensions/cornerstone/src/OHIFCornerstoneViewport.js
  yarn.lock
Labels: PR: Awaiting Review :eyes:

#1773 fix: OIDC Redirect erases query parameters
  platform/viewer/src/OHIFStandaloneViewer.js
  platform/viewer/src/routes/CallbackPage.js
Labels: PR: Awaiting Review :eyes:

#1732 fix: 🐛 Disable seg panel when data for seg unavailable
  extensions/cornerstone/package.json
  extensions/dicom-html/package.json
  extensions/dicom-rt/package.json
  extensions/dicom-segmentation/package.json
  extensions/dicom-segmentation/src/components/SegmentationPanel/SegmentationPanel.css
  extensions/dicom-segmentation/src/components/SegmentationPanel/SegmentationPanel.js
  extensions/dicom-segmentation/src/index.js
  extensions/vtk/package.json
  platform/core/package.json
  platform/viewer/cypress/integration/common/OHIFStudyList.spec.js
  platform/viewer/package.json
  yarn.lock
Labels: PR: Awaiting Review :eyes:

#1795 Fix: #1776 - Segmentations not loading
  platform/core/src/classes/metadata/StudyMetadata.js
  platform/viewer/cypress/integration/common/OHIFStudyList.spec.js
  platform/viewer/cypress/support/commands.js
  platform/viewer/src/connectedComponents/ViewerRetrieveStudyData.js
Labels: PR: Awaiting Review :eyes:

#1778 Feat/1746 idc dev tool
  extensions/dicom-p10-downloader/src/commandsModule.js
  extensions/dicom-p10-downloader/src/downloadAndZip.js
  extensions/dicom-p10-downloader/src/utils.js
Labels: PR: Awaiting Review :eyes:

#1812 OHIF-152: Create window level dropdown menu
  extensions/default/src/ViewerLayout/index.jsx
  modes/longitudinal/src/toolbarButtons.js
  platform/core/src/services/ToolBarService/ToolBarService.js
  platform/ui/index.js
  platform/ui/src/components/ExpandableToolbarButton/ExpandableToolbarButton.css
  platform/ui/src/components/ExpandableToolbarButton/ExpandableToolbarButton.jsx
  platform/ui/src/components/ExpandableToolbarButton/ExpandableToolbarButton.mdx
  platform/ui/src/components/ExpandableToolbarButton/index.js
  platform/ui/src/components/IconButton/IconButton.jsx
  platform/ui/src/components/ListMenu/ListMenu.jsx
  platform/ui/src/components/ListMenu/ListMenu.mdx
  platform/ui/src/components/ListMenu/index.js
  platform/ui/src/components/Select/Select.jsx
  platform/ui/src/components/Tooltip/Tooltip.jsx
  platform/ui/src/components/index.js
  platform/ui/tailwind.config.js
Labels: modes redesign

#1806 OHIF-151: Replace the "..." icon in more menu with active tool in menu.
  extensions/default/src/ViewerLayout/ToolbarButtonNestedMenu.jsx
  extensions/default/src/ViewerLayout/index.jsx
  extensions/default/src/getToolbarModule.js
  platform/core/src/services/ToolBarService/ToolBarService.js
  platform/ui/src/components/ToolbarButton/ToolbarButton.jsx
Labels: modes redesign

#1811 [OHIF-177] - First pass at SR STOW with Arrow Annotate, Ellipse, Length and Bidirectional.
  extensions/cornerstone/package.json
  extensions/cornerstone/src/utils/measurementServiceMappings/ArrowAnnotate.js
  extensions/default/package.json
  extensions/default/src/DicomWebDataSource/index.js
  extensions/default/src/Panels/WrappedPanelStudyBrowser.jsx
  extensions/dicom-html/package.json
  extensions/dicom-rt/package.json
  extensions/dicom-segmentation/package.json
  extensions/dicom-sr/package.json
  extensions/measurement-tracking/package.json
  extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/ActionButtons.jsx
  extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/index.js
  extensions/vtk/package.json
  platform/core/package.json
  platform/core/src/DICOMSR/dataExchange.js
  platform/core/src/DICOMSR/index.js
  platform/core/src/DataSources/IWebApiDataSource.js
  platform/viewer/package.json
  yarn.lock
Labels: modes redesign

#1799 feat: Modal + ViewportDownloadForm
  extensions/cornerstone/src/CornerstoneViewportDownloadForm.js
  platform/core/src/services/UIModalService/index.js
  platform/ui/index.js
  platform/ui/src/assets/icons/close.svg
  platform/ui/src/assets/icons/link.svg
  platform/ui/src/assets/icons/unlink.svg
  platform/ui/src/components/Icon/getIcon.jsx
  platform/ui/src/components/IconButton/IconButton.jsx
  platform/ui/src/components/Input/Input.jsx
  platform/ui/src/components/InputText/InputText.jsx
  platform/ui/src/components/Modal/Modal.css
  platform/ui/src/components/Modal/Modal.jsx
  platform/ui/src/components/Select/Select.jsx
  platform/ui/src/components/StudyListFilter/StudyListFilter.jsx
  platform/ui/src/components/ViewportDownloadForm/ViewportDownloadForm.jsx
  platform/ui/src/components/ViewportDownloadForm/index.js
  platform/ui/src/components/index.js
  platform/ui/src/contextProviders/ModalComponent.jsx
  platform/ui/src/contextProviders/ModalProvider.jsx
  platform/ui/tailwind.config.js
Labels: modes redesign

#1803 Feat/ui v2 dropdown
  extensions/default/package.json
  extensions/default/src/ViewerLayout/Header.jsx
  platform/ui/index.js
  platform/ui/src/assets/icons/link.svg
  platform/ui/src/assets/icons/unlink.svg
  platform/ui/src/components/Dropdown/Dropdown.jsx
  platform/ui/src/components/Dropdown/Dropdown.mdx
  platform/ui/src/components/Dropdown/index.js
  platform/ui/src/components/NavBar/NavBar.jsx
  platform/ui/src/components/index.js
  platform/viewer/src/App.jsx
  platform/viewer/src/components/PreferencesDropdown/PreferencesDropdown.jsx
  platform/viewer/src/components/PreferencesDropdown/index.js
  platform/viewer/src/routes/WorkList/WorkList.jsx
Labels: modes redesign

#1814 [OHIF-154] Dannyrb/ohif 154/restore command functionality for toolbar
  extensions/cornerstone/src/commandsModule.js
  extensions/cornerstone/src/init.js
  extensions/default/src/Toolbar/ToolbarLayoutSelector.jsx
  extensions/dicom-sr/src/OHIFCornerstoneSRViewport.js
  extensions/measurement-tracking/src/panels/PanelStudyBrowserTracking/PanelStudyBrowserTracking.jsx
  extensions/measurement-tracking/src/viewports/TrackedCornerstoneViewport.js
  platform/core/src/index.js
  platform/core/src/services/ViewportGridService/ViewportGridService.js
  platform/core/src/services/ViewportGridService/index.js
  platform/core/src/services/index.js
  platform/ui/src/contextProviders/ViewportGridProvider.jsx
  platform/viewer/src/App.jsx
  platform/viewer/src/appInit.js
  platform/viewer/src/components/ViewportGrid.jsx
Labels: modes redesign

#1827 OHIF-127-196-191: Hotkeys config and defaults
  modes/example/src/index.js
  modes/longitudinal/src/index.js
  modes/longitudinal/src/toolbarButtons.js
  platform/core/src/classes/HotkeysManager.js
  platform/core/src/defaults/hotkeyBindings.js
  platform/core/src/defaults/index.js
  platform/core/src/defaults/windowLevelPresets.js
  platform/core/src/index.js
  platform/core/src/index.test.js
  platform/core/src/redux/reducers/preferences.js
  platform/ui/src/components/ViewportPane/ViewportPane.jsx
  platform/viewer/src/App.jsx
  platform/viewer/src/appInit.js
  platform/viewer/src/components/ViewportGrid.jsx
  platform/viewer/src/customHooks/useQuery.js
  platform/viewer/src/routes/Mode/Mode.jsx
  platform/viewer/src/routes/buildModeRoutes.js
  platform/viewer/src/routes/index.js
Labels: modes redesign

#1822 [OHIF-192] - Viewport letter only if using multiple viewport layout.
  extensions/dicom-sr/src/OHIFCornerstoneSRViewport.js
  extensions/measurement-tracking/src/panels/PanelStudyBrowserTracking/PanelStudyBrowserTracking.jsx
  extensions/measurement-tracking/src/viewports/TrackedCornerstoneViewport.js
  platform/ui/src/components/ViewportActionBar/ViewportActionBar.jsx
Labels: PR: Awaiting Revisions :pen:, modes redesign

#1831 OHIF-203: Add new viewport overlay
  extensions/measurement-tracking/src/getViewportModule.js
  extensions/measurement-tracking/src/viewports/TrackedCornerstoneViewport.js
  extensions/measurement-tracking/src/viewports/ViewportOverlay.js
  platform/core/src/services/ToolBarService/ToolBarService.js
  platform/ui/tailwind.config.js
Labels: PR: Awaiting Response :speech_balloon:, modes redesign

#1834 OHIF-198 - Jump to thumbnail when a new displaySet is added
  extensions/default/src/Panels/PanelStudyBrowser.jsx
  extensions/dicom-sr/src/getSopClassHandlerModule.js
  extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/index.js
  extensions/measurement-tracking/src/panels/PanelStudyBrowserTracking/PanelStudyBrowserTracking.jsx
  platform/core/src/services/DisplaySetService/DisplaySetService.js
  platform/ui/src/components/Thumbnail/Thumbnail.jsx
  platform/ui/src/components/ThumbnailList/ThumbnailList.jsx
  platform/ui/src/components/ThumbnailNoImage/ThumbnailNoImage.jsx
  platform/ui/src/components/ThumbnailTracked/ThumbnailTracked.jsx
Labels: modes redesign

#1836 OHIF-179: UI for successful posting of SR data to PACS.
  extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/index.js
  platform/core/src/DICOMSR/dataExchange.js
  platform/ui/src/assets/icons/close.svg
  platform/ui/src/components/IconButton/IconButton.jsx
  platform/ui/src/components/Snackbar/Snackbar.css
  platform/ui/src/components/Snackbar/SnackbarContainer.jsx
  platform/ui/src/components/Snackbar/SnackbarItem.jsx
  platform/ui/src/contextProviders/DialogProvider.css
  platform/ui/src/contextProviders/DialogProvider.jsx
  platform/ui/tailwind.config.js
Labels: modes redesign
