Repository OHIF/Viewers, pull requests merged in 2020-08, with the labels that each got.

#1952 [OHIF-309] - Users should be able to delete an SR from the side panel when the behavior is supported by the data source
  extensions/cornerstone/src/init.js
  extensions/default/src/DicomWebDataSource/dcm4cheeReject.js
  extensions/default/src/DicomWebDataSource/index.js
  extensions/dicom-sr/src/OHIFCornerstoneSRViewport.js
  extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/index.js
  extensions/measurement-tracking/src/panels/PanelStudyBrowserTracking/PanelStudyBrowserTracking.jsx
  extensions/measurement-tracking/src/panels/PanelStudyBrowserTracking/index.jsx
  platform/core/src/DataSources/IWebApiDataSource.js
  platform/core/src/services/DisplaySetService/DisplaySetService.js
  platform/core/src/services/DisplaySetService/EVENTS.js
  platform/ui/src/components/Dialog/Header.js
  platform/ui/src/components/ThumbnailList/ThumbnailList.jsx
  platform/ui/src/components/ThumbnailNoImage/ThumbnailNoImage.jsx
  platform/viewer/public/config/default.js
  platform/viewer/public/config/netlify.js
Labels: PR: Awaiting Revisions :pen:

#1976 [OHIF-326] Export as CSV.
  extensions/cornerstone/package.json
  extensions/cornerstone/src/utils/measurementServiceMappings/EllipticalRoi.js
  extensions/dicom-rt/package.json
  extensions/dicom-segmentation/package.json
  extensions/dicom-sr/package.json
  extensions/measurement-tracking/package.json
  extensions/measurement-tracking/src/_shared/downloadCSVReport.js
  extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/ActionButtons.jsx
  extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/index.js
  extensions/vtk/package.json
  platform/core/package.json
  platform/core/src/services/MeasurementService/MeasurementService.js
  platform/viewer/package.json
  yarn.lock
Labels: PR: Awaiting Response :speech_balloon:

#1981 OHIF-298: Fix dropdown color in win browsers
  extensions/default/src/ViewerLayout/index.jsx
  platform/ui/src/components/Header/Header.jsx
  platform/ui/src/components/Select/Select.jsx
  platform/ui/src/components/StudyListPagination/StudyListPagination.js
  platform/viewer/src/routes/WorkList/WorkList.jsx
Labels: PR: Awaiting Revisions :pen:

#1985 OHIF-329: Increase fetch limit when paginating more than 101 studies
  extensions/default/src/DicomWebDataSource/index.js
  platform/ui/src/components/NavBar/NavBar.jsx
  platform/viewer/src/routes/DataSourceWrapper.jsx
  platform/viewer/src/routes/WorkList/WorkList.jsx
Labels: PR: Awaiting Revisions :pen:

#2001 Update react-cornerstone-viewport to version 4.0.2
  extensions/cornerstone/package.json
  yarn.lock
Labels: Community: PR :tada:

#1992 fix: 🐛 Fail gracefully on an MPR load error
  extensions/vtk/package.json
  extensions/vtk/src/LoadingIndicator.js
  extensions/vtk/src/OHIFVTKViewport.js
  extensions/vtk/src/index.js
  yarn.lock
Labels: PR: Awaiting Response :speech_balloon:
