Repository OHIF/Viewers, pull requests merged in 2020-02, with the labels that each got.

#1358 Remove trash data from redux storage after updates
  platform/core/src/redux/reducers/viewports.js
  platform/core/src/redux/reducers/viewports.test.js
Labels: PR: Awaiting Review :eyes:

#1420 feature: lesion-tracker extension
  extensions/lesion-tracker/.webpack/webpack.dev.js
  extensions/lesion-tracker/.webpack/webpack.prod.js
  extensions/lesion-tracker/LICENSE
  extensions/lesion-tracker/README.md
  extensions/lesion-tracker/package.json
  extensions/lesion-tracker/src/index.js
  package.json
  platform/viewer/.webpack/webpack.pwa.js
  platform/viewer/package.json
  platform/viewer/src/index-lesion-tracker.js
  yarn.lock
Labels: PR: Draft

#1314 feat: 🎸 MeasurementService
  extensions/cornerstone/babel.config.js
  extensions/cornerstone/jest.config.js
  extensions/cornerstone/package.json
  extensions/cornerstone/src/init.js
  extensions/cornerstone/src/utils/measurementServiceMappings/measurementServiceMappingsFactory.js
  extensions/cornerstone/src/utils/measurementServiceMappings/measurementServiceMappingsFactory.test.js
  jest.config.js
  platform/core/src/index.js
  platform/core/src/index.test.js
  platform/core/src/services/MeasurementService/MeasurementService.js
  platform/core/src/services/MeasurementService/MeasurementService.test.js
  platform/core/src/services/MeasurementService/index.js
  platform/core/src/services/index.js
  platform/viewer/src/App.js
Labels: PR: Awaiting Revisions :pen:, Story :raised_hands:

#1428 WIP: Lesion tracker right panel
  extensions/lesion-tracker/src/components/MeasurementComparisonTable.css
  extensions/lesion-tracker/src/components/MeasurementComparisonTable.js
  extensions/lesion-tracker/src/index.js
  platform/ui/src/components/measurementTable/MeasurementTable.js
  platform/ui/src/components/measurementTable/MeasurementTable.styl
  platform/ui/src/components/measurementTable/MeasurementTableItem.js
  platform/ui/src/components/tableList/TableList.styl
Labels: PR: Draft

#1446 Creating 2 commands to activate zoom tool and also to move between di…
  extensions/cornerstone/src/commandsModule.js
  platform/viewer/public/config/default.js
  platform/viewer/public/config/demo.js
  platform/viewer/public/config/netlify.js
  platform/viewer/src/appExtensions/GenericViewerCommands/commandsModule.js
Labels: PR: Awaiting Review :eyes:
