Repository OHIF/Viewers, pull requests merged in 2020-07, with the labels that each got.

#1841 Dannyrb/ohif 157/default to primary study expanded
  extensions/default/src/Panels/PanelStudyBrowser.jsx
  extensions/measurement-tracking/src/panels/PanelStudyBrowserTracking/PanelStudyBrowserTracking.jsx
Labels: modes redesign

#1843 Dannyrb/polish viewport notification save round trip
  extensions/measurement-tracking/src/_shared/createReportAsync.js
  extensions/measurement-tracking/src/contexts/TrackedMeasurementsContext/TrackedMeasurementsContext.jsx
  extensions/measurement-tracking/src/contexts/TrackedMeasurementsContext/promptBeginTracking.js
  extensions/measurement-tracking/src/contexts/TrackedMeasurementsContext/promptTrackNewSeries.js
  extensions/measurement-tracking/src/contexts/TrackedMeasurementsContext/promptTrackNewStudy.js
  extensions/measurement-tracking/src/getContextModule.js
  extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/index.js
Labels: modes redesign

#1835 OHIF-190 - Rehydrate PR
  extensions/cornerstone/package.json
  extensions/cornerstone/src/init.js
  extensions/cornerstone/src/utils/measurementServiceMappings/ArrowAnnotate.js
  extensions/cornerstone/src/utils/measurementServiceMappings/Bidirectional.js
  extensions/cornerstone/src/utils/measurementServiceMappings/EllipticalRoi.js
  extensions/cornerstone/src/utils/measurementServiceMappings/Length.js
  extensions/dicom-sr/src/OHIFCornerstoneSRViewport.js
  extensions/dicom-sr/src/getSopClassHandlerModule.js
  extensions/dicom-sr/src/index.js
  extensions/dicom-sr/src/utils/addMeasurement.js
  extensions/dicom-sr/src/utils/getToolStateToCornerstoneMeasurementSchema.js
  extensions/dicom-sr/src/utils/isRehydratable.js
  extensions/measurement-tracking/src/contexts/TrackedMeasurementsContext/measurementTrackingMachine.js
  extensions/measurement-tracking/src/viewports/TrackedCornerstoneViewport.js
  platform/core/src/services/MeasurementService/MeasurementService.js
  platform/ui/src/components/ViewportActionBar/ViewportActionBar.jsx
  platform/viewer/src/components/ViewportGrid.jsx
Labels: modes redesign

#1846 [OHIF-200] - Add callouts to all DICOM SR read only measurements.
  extensions/dicom-html/package.json
  extensions/dicom-rt/package.json
  extensions/dicom-segmentation/package.json
  extensions/dicom-sr/package.json
  extensions/dicom-sr/src/getSopClassHandlerModule.js
  extensions/dicom-sr/src/tools/DICOMSRDisplayTool.js
  extensions/dicom-sr/src/utils/addMeasurement.js
  extensions/measurement-tracking/package.json
  extensions/measurement-tracking/src/contexts/TrackedMeasurementsContext/measurementTrackingMachine.js
  extensions/vtk/package.json
  platform/core/package.json
  platform/viewer/package.json
  yarn.lock
Labels: modes redesign

#1852 OHIF-236: Measurement Table items should round measurements to two decimal places; matching cornerstone's rendered value
  extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/index.js
Labels: modes redesign

#1849 [OHIF-235] Lazy processing of DICOM SR for viewport.
  extensions/dicom-sr/src/OHIFCornerstoneSRViewport.js
  extensions/dicom-sr/src/getSopClassHandlerModule.js
  extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/index.js
  platform/viewer/src/components/ViewportGrid.jsx
Labels: modes redesign

#1842 OHIF-208
  extensions/cornerstone/package.json
  extensions/cornerstone/src/OHIFCornerstoneViewport.js
  extensions/cornerstone/src/commandsModule.js
  extensions/cornerstone/src/init.js
  extensions/default/src/PanelMeasurementTable.js
  extensions/dicom-rt/src/components/RTPanel/RTPanel.js
  extensions/dicom-segmentation/src/components/SegmentationPanel/SegmentationPanel.js
  extensions/dicom-sr/package.json
  extensions/dicom-sr/src/getSopClassHandlerModule.js
  extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/index.js
  extensions/measurement-tracking/src/viewports/TrackedCornerstoneViewport.js
  extensions/measurement-tracking/src/viewports/ViewportOverlay.js
  extensions/vtk/src/OHIFVTKViewport.js
  extensions/vtk/src/commandsModule.js
  platform/core/src/DICOMSR/parseDicomStructuredReport.js
  platform/core/src/services/MeasurementService/MeasurementService.js
  platform/ui/src/components/Dialog/Body.js
  platform/ui/src/components/Dialog/Dialog.jsx
  platform/ui/src/components/Dialog/Footer.js
  platform/ui/src/components/Dialog/Header.js
  platform/ui/src/components/Input/Input.jsx
  platform/ui/src/components/MeasurementTable/MeasurementItem.js
  platform/ui/src/components/MeasurementTable/MeasurementTable.jsx
  platform/ui/src/components/StudySummary/StudySummary.mdx
  platform/ui/src/contextProviders/DialogProvider.jsx
  platform/ui/src/contextProviders/ViewportGridProvider.jsx
  platform/viewer/src/appExtensions/GenericViewerCommands/commandsModule.js
  platform/viewer/src/appExtensions/MeasurementsPanel/jumpToRowItem.js
  platform/viewer/src/components/EmptyViewport.jsx
  platform/viewer/src/components/Header/Header.css
  platform/viewer/src/components/Header/Header.js
  platform/viewer/src/components/SidePanel.css
  platform/viewer/src/customHooks/useQuery.js
  yarn.lock
Labels: modes redesign

#1847 fix: General UI fixes
  extensions/measurement-tracking/src/_shared/createReportAsync.js
  extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/ActionButtons.jsx
  extensions/measurement-tracking/src/panels/PanelStudyBrowserTracking/PanelStudyBrowserTracking.jsx
  platform/ui/src/components/Button/Button.jsx
  platform/ui/src/components/ButtonGroup/ButtonGroup.jsx
  platform/ui/src/components/IconButton/IconButton.jsx
  platform/ui/src/components/Thumbnail/Thumbnail.jsx
  platform/ui/src/components/ThumbnailList/ThumbnailList.jsx
  platform/ui/src/components/ThumbnailNoImage/ThumbnailNoImage.jsx
  platform/ui/src/components/ThumbnailTracked/ThumbnailTracked.jsx
  platform/ui/src/components/ViewportActionBar/ViewportActionBar.jsx
  platform/ui/src/components/ViewportPane/ViewportPane.jsx
  platform/ui/src/gatsby-theme-docz/tailwind.css
  platform/ui/tailwind.config.js
Labels: modes redesign

#1859 OHIF-252: "Recent" and "All" tabs should be disabled if there are no studies on their category
  platform/ui/src/components/Button/Button.jsx
  platform/ui/src/components/StudyBrowser/StudyBrowser.jsx
Labels: modes redesign

#1858 OHIF-202: Add tooltip for locked/unlocked SR viewport icon
  platform/ui/src/components/MeasurementTable/MeasurementTable.jsx
  platform/ui/src/components/ViewportActionBar/ViewportActionBar.jsx
Labels: modes redesign

#1854 [OHIF-248] - Update cornerstoneTools version to get handle rendering improvements.
  extensions/cornerstone/package.json
  extensions/cornerstone/src/init.js
  extensions/dicom-rt/package.json
  extensions/dicom-segmentation/package.json
  extensions/dicom-sr/package.json
  extensions/measurement-tracking/package.json
  extensions/vtk/package.json
  platform/core/package.json
  platform/viewer/package.json
  yarn.lock
Labels: PR: Awaiting Response :speech_balloon:, modes redesign

#1837 OHIF-8: Pass fuzzymatching option from config
  extensions/default/src/DicomWebDataSource/index.js
  extensions/default/src/DicomWebDataSource/qido.js
  platform/viewer/public/config/default.js
  platform/viewer/public/config/netlify.js
Labels: PR: Draft, modes redesign

#1885 [OHIF-288] Rehydrating SRs is missing Labels
  extensions/cornerstone/package.json
  extensions/default/package.json
  extensions/dicom-html/package.json
  extensions/dicom-rt/package.json
  extensions/dicom-segmentation/package.json
  extensions/dicom-sr/package.json
  extensions/dicom-sr/src/OHIFCornerstoneSRViewport.js
  extensions/dicom-sr/src/getSopClassHandlerModule.js
  extensions/dicom-sr/src/tools/DICOMSRDisplayTool.js
  extensions/dicom-sr/src/utils/getLabelFromDCMJSImportedToolData.js
  extensions/dicom-sr/src/utils/getToolStateToCornerstoneMeasurementSchema.js
  extensions/measurement-tracking/package.json
  extensions/measurement-tracking/src/_shared/createReportAsync.js
  extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/index.js
  extensions/vtk/package.json
  platform/core/package.json
  platform/core/src/DICOMSR/dataExchange.js
  platform/viewer/package.json
  yarn.lock
Labels: PR: Awaiting Response :speech_balloon:, modes redesign

#1894 feat: OHIF-331 - About Modal
  platform/ui/src/assets/icons/external-link.svg
  platform/ui/src/components/Icon/getIcon.jsx
  platform/viewer/package.json
  platform/viewer/src/components/PreferencesDropdown/AboutModal.jsx
  platform/viewer/src/components/PreferencesDropdown/PreferencesDropdown.jsx
Labels: modes redesign

#1889 [OHIF 284] - JumpToMeasurement + prevent layout change on scroll Prevent layout change on scroll
  extensions/cornerstone/package.json
  extensions/cornerstone/src/commandsModule.js
  extensions/cornerstone/src/init.js
  extensions/cornerstone/src/utils/measurementServiceMappings/ArrowAnnotate.js
  extensions/cornerstone/src/utils/measurementServiceMappings/Bidirectional.js
  extensions/cornerstone/src/utils/measurementServiceMappings/EllipticalRoi.js
  extensions/cornerstone/src/utils/measurementServiceMappings/Length.js
  extensions/cornerstone/src/utils/measurementServiceMappings/measurementServiceMappingsFactory.js
  extensions/default/package.json
  extensions/dicom-html/package.json
  extensions/dicom-rt/package.json
  extensions/dicom-segmentation/package.json
  extensions/dicom-sr/package.json
  extensions/dicom-sr/src/OHIFCornerstoneSRViewport.js
  extensions/dicom-sr/src/utils/getToolStateToCornerstoneMeasurementSchema.js
  extensions/measurement-tracking/package.json
  extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/index.js
  extensions/measurement-tracking/src/viewports/TrackedCornerstoneViewport.js
  extensions/vtk/package.json
  platform/core/package.json
  platform/core/src/services/DisplaySetService/DisplaySetService.js
  platform/core/src/services/MeasurementService/MeasurementService.js
  platform/ui/src/contextProviders/ViewportGridProvider.jsx
  platform/viewer/package.json
  platform/viewer/src/components/ViewportGrid.jsx
  yarn.lock
Labels: modes redesign

#1887 Feat/OHIF-304 - Copying from Study List
  platform/ui/index.js
  platform/ui/src/assets/icons/clipboard.svg
  platform/ui/src/components/Icon/getIcon.jsx
  platform/ui/src/components/StudyListTable/StudyListTableRow.js
  platform/ui/src/components/TooltipClipboard/TooltipClipboard.jsx
  platform/ui/src/components/TooltipClipboard/TooltipClipboard.mdx
  platform/ui/src/components/TooltipClipboard/index.js
  platform/ui/src/components/index.js
  platform/viewer/src/routes/WorkList/WorkList.jsx
Labels: modes redesign

#1873 fix: OHIF-260 - "Clear Filters" button should not be visible on first load, when no filters are set
  platform/ui/src/components/StudyListPagination/StudyListPagination.js
  platform/viewer/src/routes/WorkList/WorkList.jsx
Labels: PR: Awaiting Revisions :pen:, modes redesign

#1886 fix: OHIF-307 - Click outside patient info should close tooltip
  platform/ui/src/components/Thumbnail/Thumbnail.jsx
  platform/ui/src/components/ThumbnailNoImage/ThumbnailNoImage.jsx
  platform/ui/src/components/ViewportActionBar/ViewportActionBar.jsx
  platform/ui/src/utils/blurHandlerListener.js
  platform/ui/src/utils/useOnClickOutside.js
Labels: PR: Awaiting Response :speech_balloon:, modes redesign

#1774 Update README.md
  platform/viewer/README.md
Labels: Stale :baguette_bread:

#1875 fix: OHIF-215 - Patient information should truncate w/ ellipsis instead of expanding box
  platform/ui/src/components/ViewportActionBar/ViewportActionBar.jsx
Labels: modes redesign
