Repository OHIF/Viewers, pull requests merged in 2020-03, with the labels that each got.

#1453 #1449 - GCloud dataset picker dialog broken
  platform/viewer/src/googleCloud/DatasetPicker.js
  platform/viewer/src/googleCloud/DatasetSelector.js
  platform/viewer/src/googleCloud/DicomStorePicker.js
  platform/viewer/src/googleCloud/DicomStorePickerModal.js
  platform/viewer/src/googleCloud/LocationPicker.js
  platform/viewer/src/googleCloud/ProjectPicker.js
Labels: PR: Bug Fix :bug:

#1333 fix for correct read of LazyMode loader setting
  platform/core/src/studies/services/wado/retrieveMetadata.js
Labels: Bug: Verified :bug:

#1492 GroupButton component and docz
  platform/ui/src/components/Button/Button.mdx
  platform/ui/src/components/ButtonGroup/ButtonGroup.jsx
  platform/ui/src/components/ButtonGroup/ButtonGroup.mdx
  platform/ui/src/components/ButtonGroup/index.js
  platform/ui/src/components/Input/Input.mdx
  platform/ui/src/components/Label/Label.mdx
  platform/ui/src/components/Typography/Typography.mdx
  platform/ui/tailwind.config.js
Labels: PR: Awaiting Response :speech_balloon:

#1497 feat: Study List Table - v2
  platform/ui/index.js
  platform/ui/src/assets/icons/instances-active.svg
  platform/ui/src/assets/icons/instances-inactive.svg
  platform/ui/src/components/Button/Button.jsx
  platform/ui/src/gatsby-theme-docz/tailwind.css
  platform/ui/src/mocks/studyList.json
  platform/ui/src/views/StudyList/StudyList.js
  platform/ui/src/views/StudyList/StudyList.mdx
  platform/ui/src/views/StudyList/components/Header.js
  platform/ui/src/views/StudyList/components/StudyListFilter.js
  platform/ui/src/views/StudyList/components/StudyListPagination.js
  platform/ui/src/views/StudyList/components/StudyListTable.js
  platform/ui/src/views/StudyList/index.js
  platform/ui/src/views/index.js
  platform/ui/tailwind.config.js
  platform/viewer/src/components/StudyList/components/StudyListTable.js
  platform/viewer/src/components/StudyList/index.js
  platform/viewer/src/connectedComponents/ConnectedStudyList.js
Labels: PR: Awaiting Review :eyes:

#1557 E2E tests for W/L Presets
  platform/viewer/cypress/integration/common/OHIFUserPreferences.spec.js
  platform/viewer/cypress/integration/visual-regression/PercyCheckOHIFExtensionPDF.spec.js
  platform/viewer/cypress/integration/visual-regression/PercyCheckOHIFUserPreferences.spec.js
  platform/viewer/cypress/support/aliases.js
  platform/viewer/cypress/support/commands.js
Labels: PR: Awaiting Revisions :pen:, Task: Tests :microscope:
