Repository OHIF/Viewers, pull requests merged in 2022-01, with the labels that each got.

#2642 fix: dicom json launch and documentation
  extensions/default/src/DicomJSONDataSource/index.js
  platform/docs/docs/assets/img/dicom-json-public.png
  platform/docs/docs/assets/img/dicom-json.png
  platform/docs/docs/configuration/dataSources/_category_.json
  platform/docs/docs/configuration/dataSources/dicom-json.md
  platform/docs/docs/configuration/dataSources/dicom-web.md
  platform/docs/docs/configuration/dataSources/static-files.md
Labels: OHIF-v3

#2632 feature: configurable max prefetch request count
  platform/core/src/classes/StudyPrefetcher.js
  platform/viewer/public/config/default.js
Labels: Community: PR :tada:

#2605 Fix/v3 scrollbars
  platform/ui/src/assets/styles/styles.css
  platform/ui/src/components/MeasurementTable/MeasurementTable.jsx
  platform/ui/src/components/StudyBrowser/StudyBrowser.jsx
  platform/ui/src/components/ThumbnailList/ThumbnailList.jsx
Labels: OHIF-v3

#2606 fix(OHIFv3):Fixed a static wado query failing to match modalities in …
  extensions/default/src/DicomWebDataSource/utils/StaticWadoClient.js
Labels: OHIF-v3

#2672 IDC update dcmjs to v0.19.2
  extensions/cornerstone/package.json
  extensions/dicom-html/package.json
  extensions/dicom-rt/package.json
  extensions/dicom-segmentation/package.json
  extensions/dicom-tag-browser/package.json
  extensions/vtk/package.json
  platform/core/package.json
  platform/viewer/package.json
  yarn.lock
Labels: IDC:priority

#2641 feat(OHIFv3):Add theme/config-point capability and docs.
  extensions/cornerstone/src/commandsModule.js
  package.json
  platform/core/src/utils/StackManager.js
  platform/docs/docs/configuration/configuration.md
  platform/docs/docs/configuration/theme-configuration.md
  platform/docs/docs/platform/services/config-point-service.md
  platform/viewer/package.json
  platform/viewer/public/theme/theme.json5
  platform/viewer/src/appInit.js
  yarn.lock
Labels: PR: Awaiting Review :eyes:, OHIF-v3
